name: Golden Security Pipeline
on:
  workflow_dispatch:

jobs:

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Get Default Config
        uses: actions/checkout@v2
        with:
          repository: Tomtestash/renovate-config
          token: ${{ secrets.RENOVATE_TOKEN }}
          ref: main
          path: default-renovate/
          clean: false
      - name: Add Local Repo
        run: |
          jq '.repositories=["${{ github.repository }}"]' <default-renovate/default.json >default-renovate/renovate-default.json     
      - name: Validate Config Fetch
        run: |
          cat default-renovate/renovate-default.json
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.241.11
        with:
          configurationFile: default-renovate/renovate-default.json
          token: ${{ secrets.RENOVATE_TOKEN }}

#   container-scan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           clean: false
#       - name: LS
#         run: |
#           pwd
#       - name: SBOM
#         uses: anchore/sbom-action@v0.13.1
#         with:
#           dependency-snapshot: true
#           artifact-name: sbom.json
#           path: /home/runner/work/test-juiceshop/test-juiceshop
#       - name: Cat SBOM
#         run: |
#           cat /tmp/sbom-action-*/sbom.json  
      # - name: Verify SBOM 
      #   run: |
      #     cat sbom.json
