name: Renovate
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Get Pwd
        run: |
          ls
      - name: Get Default Config
        uses: actions/checkout@v2
        with:
          repository: Tomtestash/renovate-config
          token: ${{ secrets.RENOVATE_SECRET }}
          ref: main
          path: default-renovate/
          clean: false
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: default-renovate/default.json
          token: ${{ secrets.RENOVATE_SECRET }}

