name: Golden Security Pipeline
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
      - name: ls
        run: |
          ls
      - name: Make log output-file
        run: | 
          touch sbom.json
      - name: SBOM
        uses: anchore/sbom-action@v0.13.1
        with:
          upload-artifact: false
          dependency-snapshot: true
          artifact-name: sbom.spdx
          output-file: sbom.spdx.json
      - name: ls
        run: |
          ls      
      - name: Verify SBOM 
        run: |
          cat sbom.json


  renovate:
    runs-on: ubuntu-latest
    needs:
      container-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Get Default Config
        uses: actions/checkout@v2
        with:
          repository: Tomtestash/renovate-config
          token: ${{ secrets.RENOVATE_SECRET }}
          ref: main
          path: default-renovate/
          clean: false
      - name: Add Local Repo
        run: |
          jq '.repositories=["${{ github.repository }}"]' <default-renovate/default.json >default-renovate/renovate-default.json     
      - name: Validate Config Fetch
        run: |
          cat default-renovate/renovate-default.json
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: default-renovate/renovate-default.json
          token: ${{ secrets.RENOVATE_SECRET }}
      - name: Show Logs
        run: |
          cat /tmp/renovatelogs.json
