name: Golden Security Pipeline
on:
  workflow_dispatch:

jobs:

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate
        uses: Tomtestash/github-action-renovate@v1.0.0
        with:
          renovate_secret: ${{ secrets.RENOVATE_SECRET }}
          enable_automerge: false
#   container-scan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           clean: false
#       - name: LS
#         run: |
#           pwd
#       - name: SBOM
#         uses: anchore/sbom-action@v0.13.1
#         with:
#           dependency-snapshot: true
#           artifact-name: sbom.json
#           path: /home/runner/work/test-juiceshop/test-juiceshop
#       - name: Cat SBOM
#         run: |
#           cat /tmp/sbom-action-*/sbom.json  
      # - name: Verify SBOM 
      #   run: |
      #     cat sbom.json
