name: Renovate
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_SECRET }}
