name: Renovate
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Default
        uses: actions/checkout@v2.0.0
        with:
          repository: Tomtestash/renovate-config
          token: ${{ secrets.RENOVATE_SECRET }}
          ref: main
          path: ./default-renovate/
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Get Pwd
        run: |
          find ~/ -name default.json
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: default.json
          token: ${{ secrets.RENOVATE_SECRET }}

