name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Default
        uses: actions/checkout@v2.0.0
        with:
          repository: Tomtestash/renovate-config
          token: ${{ secrets.RENOVATE_SECRET }}
          path: default.json
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: default.json
          token: ${{ secrets.RENOVATE_SECRET }}
